use std::path::PathBuf;

use skills_manager_core::{
    AgentToolTarget, MarketplaceDocument, MarketplaceSearchEntry, MarketplaceSourceRecord,
    SkillScaffoldPreview, WorkspaceSnapshot,
};

use super::filters::{HealthFilter, PluginTargetFilter, ScopeFilter, SortKey, SourceFilter};
use super::state::{CatalogEntryState, PreviewState};
use super::types::{InstallSource, UiCatalogFormat, UiConflictPolicy, UiScope};

#[derive(Debug, Clone)]
pub enum Message {
    Refresh,
    WorkspaceLoaded(Result<WorkspaceSnapshot, String>),
    ProjectPathChanged(String),
    SearchChanged(String),
    ActiveViewSelected(super::types::ActiveView),
    ScopeFilterSelected(ScopeFilter),
    ResourceKindSelected(super::filters::ResourceKindFilter),
    HealthFilterSelected(HealthFilter),
    SourceFilterSelected(SourceFilter),
    PluginTargetFilterSelected(PluginTargetFilter),
    SortSelected(SortKey),
    SelectSkill(String),
    SelectResource(String),
    InstallSourceSelected(InstallSource),
    SourceUrlChanged(String),
    LocalSourcePathChanged(String),
    CatalogUrlChanged(String),
    DefaultDownloadPathChanged(String),
    SaveDefaultDownloadPath,
    DefaultDownloadPathSaved(Result<String, String>),
    DownloadPathOverrideChanged(String),
    InstallScopeSelected(UiScope),
    CustomInstallPathChanged(String),
    EnableAfterInstallChanged(bool),
    ConflictSelected(UiConflictPolicy),
    DownloadSource,
    Downloaded(Result<String, String>),
    PreviewInstall,
    PreviewLoaded(Result<PreviewState, String>),
    InstallPreview,
    Installed(Result<String, String>),
    LoadCatalog,
    CatalogLoaded(Result<Vec<CatalogEntryState>, String>),
    PreviewCatalogEntry(InstallSource, String),
    CatalogFormatSelected(UiCatalogFormat),
    CatalogSavePathChanged(String),
    GenerateCatalog,
    CatalogGenerated(Result<String, String>),
    CopyCatalog,
    SaveCatalog,
    CatalogSaved(Result<String, String>),
    SetSkillEnabled(PathBuf, bool),
    SkillToggled(Result<String, String>),
    RequestRemoveSkill(PathBuf),
    ConfirmRemoveSkill(PathBuf),
    SkillRemoved(Result<String, String>),
    SetPluginEnabled(String, AgentToolTarget, bool),
    PluginToggled(Result<String, String>),
    RequestRemovePlugin(String, AgentToolTarget),
    ConfirmRemovePlugin(String, AgentToolTarget),
    PluginRemoved(Result<String, String>),
    MarketplaceSourceLabelChanged(String),
    MarketplaceSourceValueChanged(String),
    MarketplaceSourceTargetSelected(AgentToolTarget),
    MarketplaceSourceProviderChanged(String),
    AddMarketplaceSource,
    MarketplaceSourceAdded(Result<MarketplaceSourceRecord, String>),
    RefreshMarketplaceSource(String),
    MarketplaceInspected(Result<MarketplaceDocument, String>),
    RequestRemoveMarketplaceSource(String),
    ConfirmRemoveMarketplaceSource(String),
    MarketplaceSourceRemoved(Result<String, String>),
    MarketplaceSearchQueryChanged(String),
    SearchMarketplace,
    MarketplaceSearchLoaded(Result<Vec<MarketplaceSearchEntry>, String>),
    PreviewMarketplaceSearchEntry(String),
    PreviewDownloaded(PathBuf),
    RequestRemoveDownload(PathBuf),
    ConfirmRemoveDownload(PathBuf),
    DownloadRemoved(Result<String, String>),
    CreateNameChanged(String),
    CreateDescriptionChanged(String),
    CreateTargetSelected(UiScope),
    CreateCustomPathChanged(String),
    CreateTagsChanged(String),
    CreateAllowedToolsChanged(String),
    CreateCompatibilityChanged(String),
    CreateLicenseChanged(String),
    CreateWhenToUseChanged(String),
    CreateDisableModelInvocationChanged(bool),
    PreviewScaffold,
    ScaffoldPreviewed(Result<SkillScaffoldPreview, String>),
    CreateSkill,
    SkillCreated(Result<SkillScaffoldPreview, String>),
    SmokeExit,
}
